### ISSUE TITLE
Matlab is not preferable

### ISSUE THREAD

**Issue by axzfkdpmrzrheue** [TsotsosLab/SMILER#1]
Too few have Matlab due to its licensing and update costs. As a user, I would've preferred a Python interface. Julia would be a second choice. I understand that Matlab can be convenient for those who have a license. Thanks.

**Comment by tkunic** [comment]
Hello! Unfortunately, many of the models which we have included in SMILER were implemented in MATLAB, and therefore a MATLAB license is necessary to run these models. However, the SMILER CLI is Python based and can be run without a MATLAB license to execute any of the models which are implemented in other languages. At the moment, those include:

- BMS
- DGII
- DVAP
- ICF
- MLNet
- SAM
- SalGAN
- oSALICON
