### ISSUE TITLE
Calling SMILER from within a python script

### ISSUE THREAD

**Issue by rutadesai** [TsotsosLab/SMILER#12]
Is there a way to call SMILER from within a python script?

Thanks!

**Comment by tkunic** [comment]
We do not provide a Python API, just a command line interface. However, if you'd like to call the smiler executable from a python script, you could do something like:

```
import subprocess

command = ["/path/to/your/smiler/executable", "run", "-e", "your_experiment.yaml"]
rc = subprocess.call(command)
```

You can do this with any smiler command. The rc value will be 0 on success, >0 on failure.
