### ISSUE TITLE
YAML is not being installed

### ISSUE THREAD

**Issue by bwijerat** [TsotsosLab/SMILER#2]
The requirements file attempts to install yaml 3.12, however that could not be installed from pip.

```
> pip install -r requirements.txt

Collecting click==4.0 (from -r requirements.txt (line 1))
Using cached https://files.pythonhosted.org/packages/0c/d5/9b5cc74d3ac814140c1a0b89534b7d148c5b399b12f69883335d9c5cc622/click-4.0-py2.py3-none-any.whl

Collecting yaml==3.12 (from -r requirements.txt (line 2))
**Could not find a version that satisfies the requirement yaml==3.12 (from -r requirements.txt (line 2)) (from versions: )
No matching distribution found for yaml==3.12 (from -r requirements.txt (line 2))**
```

Should I install another yaml package? I can populate a list using this command but unsure which one to use: `pip search yaml`

Thanks!

**Comment by tkunic** [comment]
Hi @bwijerat, thank you for the bug report! I've updated the requirements.txt file, it should work now.

Alternatively, if you are on some flavour of linux, you can also install them using your package manager (on Ubuntu, they are `python-click` and `python-yaml`).

**Comment by bwijerat** [comment]
This fix with pyyaml works for the global python environment, tested on Python 2.7. 
However when run using an Anaconda environment it produces this warning, tested on Python 3.6:

```
> pip install -r requirements.txt

Requirement already satisfied: click==4.0 in /home/bwijerat/anaconda3/lib/python3.6/site-packages (from -r requirements.txt (line 1)) (4.0)

Collecting pyyaml>=4.2b1 (from -r requirements.txt (line 2))
Installing collected packages: pyyaml
  Found existing installation: PyYAML 3.12
Cannot uninstall 'PyYAML'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.

```
So YAML is definitely broken in some respects for Anaconda. 

Thanks!
