### ISSUE TITLE
Update README with complete contributor list

### ISSUE THREAD

**Issue by tkunic** [TsotsosLab/SMILER#33]
# Background

The README currently lists contributors to the original SMILER paper: https://github.com/TsotsosLab/SMILER/blob/master/README.md?plain=1#L7-L13

However, it neglects to mention the new HMC contributors, and it erroneously lists Toni as the current Python maintainer.

Similarly, the dockerfiles maintainer field (e.g. here https://github.com/TsotsosLab/SMILER/blob/06cd138628f26b2e16eead8e05fc922041930a44/dockerfiles/Dockerfile.oSALICON) should be updated to some group email address (perhaps lab4cats or HMC or something associated with this github repo if appropriate).

# Acceptance Criteria

- The contributor list is up to date with HMC contributors, and all contact info is updated to point to a group email.

**Comment by f-wright** [comment]
Resolved with pull request #40
