### ISSUE TITLE
Adding SMILER clean options

### ISSUE THREAD

**Issue by f-wright** [TsotsosLab/SMILER#48]
Currently, the SMILER clean command is only designed to support deleting all built images and downloaded files. It could be useful to add options to clean only images and files related to a specific model. 

Deleting built images and downloaded files makes SMILER run much slower the next time since it has to redownload and build everything deleted. It would be more efficient for many users to only delete the specific files/images for the model they are trying to change, instead of those for all models.

**Comment by richanghmc** [comment]
cleaning on individual models work!
small note on syntax: ./smiler clean --model=model_name
