### ISSUE TITLE
[Matlab][QSS] Output size needs to be adjusted 

### ISSUE THREAD

**Issue by bwijerat** [TsotsosLab/SMILER#6]
Matlab model QSS is outputting at 37x64 px which deviates from the expected standard output of 369x660 px established in this project for all models. I believe the output size needs to be adjusted. 

Also it would be nice to have this expected size listed in the READ.ME so that's its clear. And currently is there anyway for the user to specify the output size?

Thanks!

**Comment by cwloka** [comment]
Thanks for catching this; the resize step had accidentally been removed shortly before release. The code has been updated now and should behave as expected.

**Comment by bwijerat** [comment]
Retested and it's now working. Thanks
