### ISSUE TITLE
[Docker] Input folder data processed at random

### ISSUE THREAD

**Issue by bwijerat** [TsotsosLab/SMILER#8]
The frames within the input folder are processed at random, it would be nice if it were processed in alpha-numerical order. This doesn't impact the final result as the host OS will automatically reorder the files in the output folder, but when running a large batch it is nice to have it run in order in case something breaks or you stop it mid way. I was only able to observe this for the docker models, unsure if this behavior is observed with the matlab models. 
```
************************************************************
************************* oSALICON *************************
************************************************************
Setting up model...
Running model...

\Running image [1/1552]: frame741.jpg
Running image [2/1552]: frame391.jpg
Running image [3/1552]: frame1406.jpg
Running image [4/1552]: frame1184.jpg
Running image [5/1552]: frame998.jpg
Running image [6/1552]: frame196.jpg
Running image [7/1552]: frame184.jpg
Running image [8/1552]: frame602.jpg
Running image [9/1552]: frame518.jpg
Running image [10/1552]: frame94.jpg
Running image [11/1552]: frame377.jpg
Running image [12/1552]: frame312.jpg
Running image [13/1552]: frame837.jpg
```
Thanks!

**Comment by tkunic** [comment]
Python dicts are hashmaps, so the order was consistent when re-running the same experiment, but it wasn't in lexicographical order. Updated v_1.1 branch to sort them first.
